#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

rm -rf testthat.buildkite
cp -r ../testthat.buildkite .

docker build --pull \
       --tag $TAG_SHA \
       -f docker/Dockerfile \
       .

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
