#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

function cleanup {
    echo "Cleaning up"
    docker stop tests_run
}
trap cleanup EXIT

rm -rf testthat.buildkite
cp -r ../testthat.buildkite .

docker run --rm -d -it --name tests_run $TAG_SHA bash

docker cp testthat.buildkite tests_run:/src/testthat.buildkite

docker exec -it tests_run R CMD INSTALL /src/testthat.buildkite
docker exec -it tests_run test_self
